export const USER_POSTS_FETCH_REQUESTED = 'USER_POSTS_FETCH_REQUESTED';
export const USER_POSTS_FETCH_SUCCEEDED = 'USER_POSTS_FETCH_SUCCEEDED';
export const USER_POSTS_FETCH_FAILED = 'USER_POSTS_FETCH_FAILED';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCEEDED = 'FETCH_USERS_SUCCEEDED';
