import Head from 'next/head'
import * as types from '../store/types';
import { useDispatch } from 'react-redux'
import styles from '../styles/Home.module.css'
import { useSelector } from 'react-redux';

export default function Home() {

  const dipatch = useDispatch();

  const handlerGetPosts = () => {
    dipatch({type: types.USER_POSTS_FETCH_REQUESTED})
    // payload: {
    //   userId: 1
    // }})
  }

  const { posts } = useSelector((state) => state.app);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      App works
      <button className='btn' onClick={handlerGetPosts}>get Posts</button>

      {
        posts &&
        posts.map((post) => (
          <>
            <div><strong>{post.title}</strong></div>
            <div>{post.body}</div>
          </>
        ))
      }

    </div>
  )
}
