import Head from 'next/head';
import * as types from '../store/types';
import { useDispatch } from 'react-redux';
import styles from '../styles/Home.module.css';
import { useSelector } from 'react-redux';

export default function Home() {
  const dipatch = useDispatch();

  const handlerGetPosts = () => {
    dipatch({ type: types.USER_POSTS_FETCH_REQUESTED });
    // payload: {
    //   userId: 1
    // }})
  };

  const handlerGetUsers = () => {
    debugger
    dipatch({ type: types.FETCH_USERS });
  };
  const { posts } = useSelector((state) => state.app);
  const { users } = useSelector((state) => state.app);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      App works
      <button className="btn" onClick={handlerGetPosts}>
        get Posts
      </button>
      <button className="btn" onClick={handlerGetUsers}>
        get Users
      </button>
      {posts &&
        posts.map((post) => (
          <>
            <div>
              <strong>{post.title}</strong>
            </div>
            <div>{post.body}</div>
          </>
        ))}
      {users &&
        users.map((user) => (
          <>
            <div>
              <strong>{user.name}</strong>
            </div>
            <div>{user.email}</div>
          </>
        ))}
    </div>
  );
}
